AWSTemplateFormatVersion: 2010-09-09
Description: "Creates a cross account role"

Parameters:
  DFDeploymentRoleName:
    Type: String
    Default: df-deployment-role

  DeploymentAccountId:
    Type: String
    Default: "624768538958"

  DFDeploymentBucketName:
    Type: String
    Default: df-deployment-artifacts
  
  MainStackName:
    Type: String
    Default: df-bootstrap-stack

  CodeBuildProjectName:
    Type: String 
    Default: df-bootstrap-build
  
  DeploymentRepositoryName:
    Type: String
    Default: df-bootstrap-repository

Resources:


  DeploymentArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref DFDeploymentBucketName


  BootstrapCodecommitRepository:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: !Ref DeploymentRepositoryName

  CrossAccountDeploymentRole: 
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref DFDeploymentRoleName
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - !Sub arn:aws:iam::${DeploymentAccountId}:root
            Action: 
              - sts:AssumeRole

  CrossAccountDeploymentPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Allows management account pipeline to execute in deployment account
      ManagedPolicyName: df-cross-account-deployment-policy
      Roles:
        - !Ref CrossAccountDeploymentRole
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: IAMRolesPermission
            Effect: Allow
            Action:
              - iam:PassRole
              - iam:GetRole
            Resources: '*'
          - Sid: S3FullAccess
            Effect: Allow
            Action:
              - 's3:*'
            Resource: '*'
          - Sid: LambdaFullAccess
            Effect: Allow
            Action: 'lambda:*'
            Resource: '*'
          - Sid: CloudFormationFullAccess
            Effect: Allow
            Action: 'cloudformation:*'
            Resource: '*'
          - Sid: AllowCloudwatch
            Effect: Allow
            Action: 
              - 'cloudwatch:*'
              - 'logs:*'
              - 'events:*'
            Resource: '*'
  

  GlobalDeploymentPipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      ArtifactStore:
        Type: S3 
        Location: !Ref DeploymentArtifactBucket
      Stages:
        - Name: Source 
          Actions:
            - Name: Source 
              ActionTypeId:
                Category: Source 
                Owner: AWS
                Version: 1
                Provider: CodeCommit
              Configuration:
                RepositoryName: df-deployment
                BranchName: main
              OutputArtifacts:
                - Name: SourceArtifact

        - Name: Build
          Actions: 
            - Name: Build
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: 1
                Provider: Codebuild
              Configuration:
                ProjectName: !Ref CodeBuildProject
              InputArtifacts:
                - Name: SourceArtifact
              OutputArtifacts:
                - Name: BuildArtifact

          StageName: Build
        - Name: Deploy
          Actions:
            - Name: Deploy
              ActionTypeId:
                Owner: AWS
                Version: 1
                Provider: Cloudformation
              Configuration: 
                ActionMode: CREATE_UPDATE
                StackName: !Ref MainStackName
                TemplatePath: BuildArtifact::template.yml
                RoleArn: !GetAtt CrossAccountDeploymentRole.Arn
              InputArtifacts:
                - Name: BuildArtifact
  

  
  
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Ref CodeBuildProjectName
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:5.0 
      Source:
        Type: CODECOMMIT
        Location: !Sub 
            


